
// Exact package-ID names from the linked store/repository pages.
// This catalogue supplies display names only. It never assigns a publisher country.
const PackageNames = (() => {
  'use strict';
  const VERSION = '2026-09-23.1';
  const CHECKED_AT = '2026-09-23';
  const listingUrl = id => `https://play.google.com/store/apps/details?id=${encodeURIComponent(id)}&hl=en`;
  const rows = [
      ["com.amazon.mShop.android.shopping","Amazon Shopping"],
      ["com.barghest.mesh","MESH","https://f-droid.org/en/packages/com.barghest.mesh/"],
      ["com.canarabank.mobility","Canara ai1- Mobile Banking App"],
      ["com.dalailama.dalailamaofficial","Dalai Lama"],
      ["com.eterno","Dailyhunt - News & Magazines"],
      ["com.evamall.evacustomer","Decathlon Sports Shopping App"],
      ["com.facebook.lite","Facebook Lite"],
      ["com.facebook.orca","Messenger"],
      ["com.flipkart.android","Flipkart Online Shopping App"],
      ["com.fsn.nykaa","Nykaa - Beauty Shopping App"],
      ["com.google.android.apps.docs","Google Drive"],
      ["com.google.android.apps.magazines","Google News - Daily Headlines"],
      ["com.google.android.apps.maps","Google Maps"],
      ["com.google.android.apps.messaging","Google Messages"],
      ["com.google.android.apps.nbu.files","Files by Google"],
      ["com.google.android.apps.nbu.paisa.user","Google Pay: Secure UPI payment"],
      ["com.google.android.apps.photos","Google Photos"],
      ["com.google.android.apps.tachyon","Google Meet"],
      ["com.google.android.apps.wellbeing","Digital Wellbeing"],
      ["com.google.android.apps.youtube.music","YouTube Music"],
      ["com.google.android.calculator","Calculator"],
      ["com.google.android.calendar","Google Calendar"],
      ["com.google.android.contacts","Contacts"],
      ["com.google.android.deskclock","Clock"],
      ["com.google.android.dialer","Phone by Google"],
      ["com.google.android.gms","Google Play services"],
      ["com.google.android.googlequicksearchbox","Google"],
      ["com.google.android.ims","Carrier Services"],
      ["com.google.android.inputmethod.latin","Gboard - the Google Keyboard"],
      ["com.google.android.keep","Google Keep - Notes and lists"],
      ["com.google.android.marvin.talkback","Android Accessibility Suite"],
      ["com.google.android.projection.gearhead","Android Auto"],
      ["com.google.android.safetycore","Android System SafetyCore"],
      ["com.google.android.tts","Speech Recognition & Synthesis"],
      ["com.google.android.videos","Google TV"],
      ["com.google.android.webview","Android System WebView"],
      ["com.google.android.youtube","YouTube"],
      ["com.google.ar.core","Google Play Services for AR"],
      ["com.google.ar.lens","Google Lens"],
      ["com.instagram.android","Instagram"],
      ["com.instagram.barcelona","Threads"],
      ["com.mi.global.shop","Mi Store"],
      ["com.microsoft.skydrive","Microsoft OneDrive"],
      ["com.microsoft.teams","Microsoft Teams"],
      ["com.netflix.mediaclient","Netflix"],
      ["com.phonepe.app","PhonePe UPI Payments, Loan App"],
      ["com.popularapp.periodcalendar","Period Calendar Period Tracker"],
      ["com.snapchat.android","Snapchat"],
      ["com.spotify.music","Spotify: Music and Podcasts"],
      ["com.twitter.android","X"],
      ["com.whatsapp","WhatsApp Messenger"],
      ["com.whatsapp.w4b","WhatsApp Business"],
      ["com.zhiliaoapp.musically","TikTok - Videos, Shop & LIVE"],
      ["in.org.npci.upiapp","BHIM Bharat's Own Payments App"],
      ["net.one97.paytm","Paytm: Secure UPI Payments"],
      ["org.fdroid.fdroid","F-Droid","https://f-droid.org/packages/org.fdroid.fdroid/"],
      ["org.telegram.messenger","Telegram"],
      ["org.thoughtcrime.securesms","Signal Private Messenger"],
      ["us.zoom.videomeetings","Zoom Workplace"],
      ["com.tibetan.two.textview","Tibetan Grammer"],
      ["com.digilocker.android","DigiLocker"],
      ["com.myntra.android","Myntra - Fashion Shopping App"],
      ["in.amazon.mShop.android.shopping","Amazon India Shop, Pay, miniTV"],
      ["com.android.chrome","Google Chrome"],
      ["org.mozilla.firefox","Firefox Fast & Private Browser"],
      ["com.brave.browser","Brave Private Browser"],
      ["com.opera.browser","Opera Browser"],
      ["com.duckduckgo.mobile.android","DuckDuckGo Privacy Browser"],
      ["com.microsoft.emmx","Microsoft Edge"],
      ["com.adobe.reader","Adobe Acrobat Reader"],
      ["com.adobe.scan.android","Adobe Scan"],
      ["com.microsoft.office.word","Microsoft Word"],
      ["com.microsoft.office.excel","Microsoft Excel"],
      ["com.microsoft.office.powerpoint","Microsoft PowerPoint"],
      ["com.microsoft.office.outlook","Microsoft Outlook"],
      ["com.microsoft.office.onenote","Microsoft OneNote"],
      ["com.microsoft.translator","Microsoft Translator"],
      ["com.microsoft.bing","Microsoft Bing Search"],
      ["com.skype.raider","Skype"],
      ["com.linkedin.android","LinkedIn"],
      ["com.github.android","GitHub"],
      ["com.yahoo.mobile.client.android.mail","Yahoo Mail"],
      ["com.reddit.frontpage","Reddit"],
      ["com.pinterest","Pinterest"],
      ["com.tumblr","Tumblr"],
      ["com.quora.android","Quora"],
      ["com.viber.voip","Viber Messenger"],
      ["com.tencent.mm","WeChat"],
      ["jp.naver.line.android","LINE"],
      ["com.discord","Discord"],
      ["com.twitch.android","Twitch"],
      ["tv.pluto.android","Pluto TV"],
      ["com.hbo.hbonow","Max: Stream HBO, TV, & Movies"],
      ["com.disney.disneyplus","Disney+"],
      ["com.hulu.plus","Hulu"],
      ["com.amazon.avod.thirdpartyclient","Amazon Prime Video"],
      ["com.roku.remote","Roku"],
      ["com.tubitv","Tubi - Free Movies & TV Shows"],
      ["com.vimeo.android.videoapp","Vimeo"],
      ["com.soundcloud.android","SoundCloud"],
      ["com.pandora.android","Pandora"],
      ["com.shazam.android","Shazam"],
      ["com.tunein.player","TuneIn Radio"],
      ["com.clearchannel.iheartradio.controller","iHeartRadio"],
      ["com.duolingo","Duolingo"],
      ["com.babbel.mobile.android.en","Babbel"],
      ["com.memrise.android.memrisecompanion","Memrise"],
      ["net.khanacademy.android","Khan Academy"],
      ["org.coursera.android","Coursera"],
      ["com.udemy.android","Udemy"],
      ["com.linkedin.android.learning","LinkedIn Learning"],
      ["com.ted.android","TED"],
      ["com.canva.editor","Canva"],
      ["com.picsart.studio","Picsart AI Photo Editor"],
      ["com.niksoftware.snapseed","Snapseed"],
      ["vsco.android.camera","VSCO"],
      ["com.cisco.webex.meetings","Webex Meetings"],
      ["com.slack","Slack"],
      ["com.trello","Trello"],
      ["com.asana.app","Asana"],
      ["com.dropbox.android","Dropbox"],
      ["com.box.android","Box"],
      ["com.evernote","Evernote"],
      ["com.todoist","Todoist"],
      ["com.anydo","Any.do"],
      ["com.ticktick.task","TickTick"],
      ["com.ebay.mobile","eBay"],
      ["com.alibaba.aliexpresshd","AliExpress"],
      ["com.contextlogic.wish","Wish"],
      ["com.zzkko","SHEIN"],
      ["com.etsy.android","Etsy"],
      ["com.walmart.android","Walmart"],
      ["com.target.ui","Target"],
      ["com.ubercab","Uber"],
      ["com.ubercab.eats","Uber Eats"],
      ["com.application.zomato","Zomato"],
      ["in.swiggy.android","Swiggy"],
      ["com.sft.makeitall","Blinkit"],
      ["com.olacabs.customer","Ola Cabs"],
      ["com.makemytrip","MakeMyTrip"],
      ["com.goibibo","Goibibo"],
      ["com.oyorooms.oyoapplication","OYO"],
      ["com.trivago","trivago"],
      ["com.tripadvisor.tripadvisor","Tripadvisor"],
      ["com.airbnb.android","Airbnb"],
      ["com.booking","Booking.com"],
      ["com.expedia.bookings","Expedia"],
      ["com.kayak.android","KAYAK"],
      ["com.skyscanner.android","Skyscanner"],
      ["com.waze","Waze"],
      ["com.sygic.aura","Sygic GPS Navigation"],
      ["com.life360.android.safetymapd","Life360"],
      ["com.fitnesskeeper.runkeeper.pro","Runkeeper"],
      ["com.stravainc.strava","Strava"],
      ["com.myfitnesspal.android","MyFitnessPal"],
      ["com.calm.android","Calm"],
      ["com.getsomeheadspace.android","Headspace"],
      ["com.alltrails.alltrails","AllTrails"],
      ["com.zillow.android.zillowmap","Zillow"],
      ["com.trulia.android.re","Trulia"],
      ["com.realtor.com","Realtor.com"],
      ["com.yelp.android","Yelp"],
      ["com.paypal.android.p2pmobile","PayPal"],
      ["com.venmo","Venmo"],
      ["com.squareup.cash","Cash App"],
      ["com.chase.sig.android","Chase Mobile"],
      ["com.wf.wellsfargomobile","Wells Fargo Mobile"],
      ["com.citi.citimobile","Citi Mobile"],
      ["com.discoverfinancial.mobile","Discover Mobile"],
      ["com.robinhood.android","Robinhood"],
      ["com.coinbase.android","Coinbase"],
      ["com.binance.dev","Binance"],
      ["com.nianticlabs.pokemongo","Pokémon GO"],
      ["com.king.candycrushsaga","Candy Crush Saga"],
      ["com.roblox.client","Roblox"],
      ["com.mojang.minecraftpe","Minecraft"],
      ["com.kiloo.subwaysurf","Subway Surfers"],
      ["com.supercell.clashofclans","Clash of Clans"],
      ["com.tencent.ig","PUBG MOBILE"],
      ["com.activision.callofduty.shooter","Call of Duty: Mobile"],
      ["com.ea.game.pvz2_row","Plants vs. Zombies 2"],
      ["com.innersloth.spacemafia","Among Us"],
      ["com.miniclip.eightballpool","8 Ball Pool"],
      ["com.playrix.homescapes","Homescapes"],
      ["com.google.android.gm","Gmail"],
      ["com.google.android.apps.translate","Google Translate"],
      ["com.google.android.apps.podcasts","Google Podcasts"],
      ["com.google.android.apps.walletnfcrel","Google Wallet"],
      ["com.google.android.apps.cultural","Google Arts & Culture"],
      ["com.google.android.apps.authenticator2","Google Authenticator"],
      ["com.google.android.apps.fitness","Google Fit"],
      ["com.google.android.play.games","Google Play Games"],
      ["com.google.earth","Google Earth"],
      ["com.google.android.apps.chromecast.app","Google Home"],
      ["com.google.android.apps.docs.editors.docs","Google Docs"],
      ["com.google.android.apps.docs.editors.sheets","Google Sheets"],
      ["com.google.android.apps.docs.editors.slides","Google Slides"],
      ["com.openai.chatgpt","ChatGPT"],
      ["com.anthropic.claude","Claude"],
      ["com.lcode.ucomobilebanking","UCO mBanking Plus"],["com.mykeyboard.myphotokeyboard.tibetankeyboard", "Tibetan Keyboard"],
      ["com.sjfc.xyzl", "Daily Tibetan Calendar"],
      ["com.codingwithtashi.tibetan_calender", "Tibetan Calendar"],
      ["com.monlamai.monlamgrantdictionary", "Monlam Grand Dictionary"],
      ["com.rahmobile.myTibetan", "myTibetan Dictionary"],
      ["com.vot.vot", "Voice of Tibet"],
      ["com.newsapp.voicefortibet", "Tibet Tribune"],
      ["com.bigkidsapps.tibetanmantras", "Tibetan Buddhist Mantras"],    
      ["cn.wps.moffice_eng","WPS Office-PDF,Word,Excel,PPT"],
      ["com.android.vending","Google Play Store","https://developer.android.com/distribute/marketing-tools/linking-to-google-play"],
      ["net.oneplus.weather","OnePlus Weather"],
      ["com.oneplus.gallery","OnePlus Gallery"],
      ["com.oneplus.filemanager","OnePlus File Manager"],
      ["com.oplus.gesture", "OPPO Gestures & Motions"],
      ["com.oplus.camera", "OPPO Camera"],
      ["com.coloros.safecenter", "ColorOS Phone Manager"],
      ["com.coloros.gallery3d", "ColorOS Photos"],
      ["com.oneplus.launcher", "OnePlus System Launcher"],
      ["com.sec.android.app.launcher", "Samsung One UI Home"],
      ["com.samsung.android.lool", "Samsung Device Care"],
      ["com.samsung.android.dialer", "Samsung Phone"],
      ["com.miui.home", "Xiaomi MIUI System Launcher"],
      ["com.miui.securitycenter", "Xiaomi Security App"],
      ["com.miui.gallery", "Xiaomi Gallery"],
      ["com.huawei.android.launcher", "Huawei EMUI Launcher"],
      ["com.android.systemui", "Android System UI"],
      ["com.android.settings", "Android Settings"],
      ["com.android.vending", "Google Play Store"],
      ["com.android.bluetooth", "Android Bluetooth Service"],
      ["com.android.nfc", "Android NFC Service"],
      ["com.google.android.packageinstaller", "Android Package Installer"],
      ["com.google.android.permissioncontroller", "Android Permission Controller"]
  ];
  const names = new Map(rows.map(([id, name, url]) => [id, Object.freeze({
    name, matched_package: id, match_method: 'exact-package-id',
    source_url: url || listingUrl(id),
    source_title: url ? 'F-Droid package listing' : 'Google Play app listing',
    checked_at: CHECKED_AT, catalogue_version: VERSION, scope: 'app-name-only',
  })]));
  if (names.size !== rows.length) throw new Error('Duplicate package ID in name catalogue.');

  function lookup(id, origin = {}) {
    const match = names.get(id);
    if (match) return { ...match };
    if (origin.match_method === 'exact-package-id' && origin.matched_package === id && origin.app_name) {
      return {
        name: origin.app_name, matched_package: id, match_method: 'exact-package-id',
        source_url: origin.sources?.[0]?.url || null,
        source_title: origin.sources?.[0]?.title || 'Publisher catalogue',
        checked_at: origin.checked_at || null, catalogue_version: origin.catalogue_version || null,
        scope: 'publisher-catalogue-name',
      };
    }
    return null;
  }

  function metadata() {
    return { version: VERSION, checked_at: CHECKED_AT, rule_count: names.size,
      scope: 'Exact-ID app names, independent of publisher and country classifications.',
      limitation: 'Store names can change and can differ from the installed label. Unmatched IDs need collector labels or additional verified entries.' };
  }
  return Object.freeze({ lookup, metadata, listingUrl });
})();
