
// Exact package-ID names from the linked store/repository pages.
// This catalogue supplies display names only. It never assigns a publisher country.
const PackageNames = (() => {
  'use strict';
  const VERSION = '2026-09-23.1';
  const CHECKED_AT = '2026-09-23';
  const listingUrl = id => `https://play.google.com/store/apps/details?id=${encodeURIComponent(id)}&hl=en`;
  const rows = [
      ["com.amazon.mShop.android.shopping","Amazon Shopping"],
      ["com.barghest.mesh","MESH","https://f-droid.org/en/packages/com.barghest.mesh/"],
      ["com.canarabank.mobility","Canara ai1- Mobile Banking App"],
      ["com.dalailama.dalailamaofficial","Dalai Lama"],
      ["com.eterno","Dailyhunt - News & Magazines"],
      ["com.evamall.evacustomer","Decathlon Sports Shopping App"],
      ["com.facebook.lite","Facebook Lite"],
      ["com.facebook.orca","Messenger"],
      ["com.flipkart.android","Flipkart Online Shopping App"],
      ["com.fsn.nykaa","Nykaa - Beauty Shopping App"],
      ["com.google.android.apps.docs","Google Drive"],
      ["com.google.android.apps.magazines","Google News - Daily Headlines"],
      ["com.google.android.apps.maps","Google Maps"],
      ["com.google.android.apps.nbu.files","Files by Google"],
      ["com.google.android.apps.nbu.paisa.user","Google Pay: Secure UPI payment"],
      ["com.google.android.apps.photos","Google Photos"],
      ["com.google.android.apps.wellbeing","Digital Wellbeing"],
      ["com.google.android.apps.youtube.music","YouTube Music"],
      ["com.google.android.calculator","Calculator"],
      ["com.google.android.calendar","Google Calendar"],
      ["com.google.android.contacts","Contacts"],
      ["com.google.android.dialer","Phone by Google"],
      ["com.google.android.gms","Google Play services"],
      ["com.google.android.ims","Carrier Services"],
      ["com.google.android.inputmethod.latin","Gboard - the Google Keyboard"],
      ["com.google.android.keep","Google Keep - Notes and lists"],
      ["com.google.android.marvin.talkback","Android Accessibility Suite"],
      ["com.google.android.projection.gearhead","Android Auto"],
      ["com.google.android.safetycore","Android System SafetyCore"],
      ["com.google.android.tts","Speech Recognition & Synthesis"],
      ["com.google.android.videos","Google TV"],
      ["com.google.android.webview","Android System WebView"],
      ["com.google.ar.core","Google Play Services for AR"],
      ["com.google.ar.lens","Google Lens"],
      ["com.instagram.android","Instagram"],
      ["com.instagram.barcelona","Threads"],
      ["com.mi.global.shop","Mi Store"],
      ["com.microsoft.skydrive","Microsoft OneDrive"],
      ["com.microsoft.teams","Microsoft Teams"],
      ["com.netflix.mediaclient","Netflix"],
      ["com.phonepe.app","PhonePe UPI Payments, Loan App"],
      ["com.popularapp.periodcalendar","Period Calendar Period Tracker"],
      ["com.snapchat.android","Snapchat"],
      ["com.spotify.music","Spotify: Music and Podcasts"],
      ["com.twitter.android","X"],
      ["com.whatsapp","WhatsApp Messenger"],
      ["com.whatsapp.w4b","WhatsApp Business"],
      ["com.zhiliaoapp.musically","TikTok - Videos, Shop & LIVE"],
      ["in.org.npci.upiapp","BHIM Bharat's Own Payments App"],
      ["net.one97.paytm","Paytm: Secure UPI Payments"],
      ["org.fdroid.fdroid","F-Droid","https://f-droid.org/packages/org.fdroid.fdroid/"],
      ["org.telegram.messenger","Telegram"],
      ["org.thoughtcrime.securesms","Signal Private Messenger"],
      ["us.zoom.videomeetings","Zoom Workplace"],
      ["com.tibetan.two.textview","Tibetan Grammer"],
      ["com.digilocker.android","DigiLocker"],
      ["com.myntra.android","Myntra - Fashion Shopping App"],
      ["in.amazon.mShop.android.shopping","Amazon India Shop, Pay, miniTV"],
      ["com.android.chrome","Google Chrome"],
      ["org.mozilla.firefox","Firefox Fast & Private Browser"],
      ["com.brave.browser","Brave Private Browser"],
      ["com.opera.browser","Opera Browser"],
      ["com.duckduckgo.mobile.android","DuckDuckGo Privacy Browser"],
      ["com.microsoft.emmx","Microsoft Edge"],
      ["com.adobe.reader","Adobe Acrobat Reader"],
      ["com.adobe.scan.android","Adobe Scan"],
      ["com.microsoft.office.word","Microsoft Word"],
      ["com.microsoft.office.excel","Microsoft Excel"],
      ["com.microsoft.office.powerpoint","Microsoft PowerPoint"],
      ["com.microsoft.office.outlook","Microsoft Outlook"],
      ["com.microsoft.office.onenote","Microsoft OneNote"],
      ["com.microsoft.translator","Microsoft Translator"],
      ["com.microsoft.bing","Microsoft Bing Search"],
      ["com.skype.raider","Skype"],
      ["com.linkedin.android","LinkedIn"],
      ["com.github.android","GitHub"],
      ["com.yahoo.mobile.client.android.mail","Yahoo Mail"],
      ["com.reddit.frontpage","Reddit"],
      ["com.pinterest","Pinterest"],
      ["com.tumblr","Tumblr"],
      ["com.quora.android","Quora"],
      ["com.viber.voip","Viber Messenger"],
      ["com.tencent.mm","WeChat"],
      ["jp.naver.line.android","LINE"],
      ["com.discord","Discord"],
      ["com.twitch.android","Twitch"],
      ["tv.pluto.android","Pluto TV"],
      ["com.hbo.hbonow","Max: Stream HBO, TV, & Movies"],
      ["com.disney.disneyplus","Disney+"],
      ["com.hulu.plus","Hulu"],
      ["com.amazon.avod.thirdpartyclient","Amazon Prime Video"],
      ["com.roku.remote","Roku"],
      ["com.tubitv","Tubi - Free Movies & TV Shows"],
      ["com.vimeo.android.videoapp","Vimeo"],
      ["com.soundcloud.android","SoundCloud"],
      ["com.pandora.android","Pandora"],
      ["com.shazam.android","Shazam"],
      ["com.tunein.player","TuneIn Radio"],
      ["com.clearchannel.iheartradio.controller","iHeartRadio"],
      ["com.duolingo","Duolingo"],
      ["com.babbel.mobile.android.en","Babbel"],
      ["com.memrise.android.memrisecompanion","Memrise"],
      ["net.khanacademy.android","Khan Academy"],
      ["org.coursera.android","Coursera"],
      ["com.udemy.android","Udemy"],
      ["com.linkedin.android.learning","LinkedIn Learning"],
      ["com.ted.android","TED"],
      ["com.canva.editor","Canva"],
      ["com.picsart.studio","Picsart AI Photo Editor"],
      ["com.niksoftware.snapseed","Snapseed"],
      ["vsco.android.camera","VSCO"],
      ["com.cisco.webex.meetings","Webex Meetings"],
      ["com.slack","Slack"],
      ["com.trello","Trello"],
      ["com.asana.app","Asana"],
      ["com.dropbox.android","Dropbox"],
      ["com.box.android","Box"],
      ["com.evernote","Evernote"],
      ["com.todoist","Todoist"],
      ["com.anydo","Any.do"],
      ["com.ticktick.task","TickTick"],
      ["com.ebay.mobile","eBay"],
      ["com.alibaba.aliexpresshd","AliExpress"],
      ["com.contextlogic.wish","Wish"],
      ["com.zzkko","SHEIN"],
      ["com.etsy.android","Etsy"],
      ["com.walmart.android","Walmart"],
      ["com.target.ui","Target"],
      ["com.ubercab","Uber"],
      ["com.ubercab.eats","Uber Eats"],
      ["com.application.zomato","Zomato"],
      ["in.swiggy.android","Swiggy"],
      ["com.sft.makeitall","Blinkit"],
      ["com.olacabs.customer","Ola Cabs"],
      ["com.makemytrip","MakeMyTrip"],
      ["com.goibibo","Goibibo"],
      ["com.oyorooms.oyoapplication","OYO"],
      ["com.trivago","trivago"],
      ["com.tripadvisor.tripadvisor","Tripadvisor"],
      ["com.airbnb.android","Airbnb"],
      ["com.booking","Booking.com"],
      ["com.expedia.bookings","Expedia"],
      ["com.kayak.android","KAYAK"],
      ["com.skyscanner.android","Skyscanner"],
      ["com.waze","Waze"],
      ["com.sygic.aura","Sygic GPS Navigation"],
      ["com.life360.android.safetymapd","Life360"],
      ["com.fitnesskeeper.runkeeper.pro","Runkeeper"],
      ["com.stravainc.strava","Strava"],
      ["com.myfitnesspal.android","MyFitnessPal"],
      ["com.calm.android","Calm"],
      ["com.getsomeheadspace.android","Headspace"],
      ["com.alltrails.alltrails","AllTrails"],
      ["com.zillow.android.zillowmap","Zillow"],
      ["com.trulia.android.re","Trulia"],
      ["com.realtor.com","Realtor.com"],
      ["com.yelp.android","Yelp"],
      ["com.paypal.android.p2pmobile","PayPal"],
      ["com.venmo","Venmo"],
      ["com.squareup.cash","Cash App"],
      ["com.chase.sig.android","Chase Mobile"],
      ["com.wf.wellsfargomobile","Wells Fargo Mobile"],
      ["com.citi.citimobile","Citi Mobile"],
      ["com.discoverfinancial.mobile","Discover Mobile"],
      ["com.robinhood.android","Robinhood"],
      ["com.coinbase.android","Coinbase"],
      ["com.binance.dev","Binance"],
      ["com.nianticlabs.pokemongo","Pokémon GO"],
      ["com.king.candycrushsaga","Candy Crush Saga"],
      ["com.roblox.client","Roblox"],
      ["com.mojang.minecraftpe","Minecraft"],
      ["com.kiloo.subwaysurf","Subway Surfers"],
      ["com.supercell.clashofclans","Clash of Clans"],
      ["com.tencent.ig","PUBG MOBILE"],
      ["com.activision.callofduty.shooter","Call of Duty: Mobile"],
      ["com.ea.game.pvz2_row","Plants vs. Zombies 2"],
      ["com.innersloth.spacemafia","Among Us"],
      ["com.miniclip.eightballpool","8 Ball Pool"],
      ["com.playrix.homescapes","Homescapes"],
      ["com.google.android.apps.translate","Google Translate"],
      ["com.google.android.apps.podcasts","Google Podcasts"],
      ["com.google.android.apps.walletnfcrel","Google Wallet"],
      ["com.google.android.apps.cultural","Google Arts & Culture"],
      ["com.google.android.apps.authenticator2","Google Authenticator"],
      ["com.google.android.apps.fitness","Google Fit"],
      ["com.google.android.play.games","Google Play Games"],
      ["com.google.earth","Google Earth"],
      ["com.google.android.apps.chromecast.app","Google Home"],
      ["com.google.android.apps.docs.editors.docs","Google Docs"],
      ["com.google.android.apps.docs.editors.sheets","Google Sheets"],
      ["com.google.android.apps.docs.editors.slides","Google Slides"],
      ["com.openai.chatgpt","ChatGPT"],
      ["com.anthropic.claude","Claude"],
      ["com.lcode.ucomobilebanking","UCO mBanking Plus"],
      ["com.mykeyboard.myphotokeyboard.tibetankeyboard", "Tibetan Keyboard"],
      ["com.sjfc.xyzl", "Daily Tibetan Calendar"],
      ["com.codingwithtashi.tibetan_calender", "Tibetan Calendar"],
      ["com.monlamai.monlamgrantdictionary", "Monlam Grand Dictionary"],
      ["com.rahmobile.myTibetan", "myTibetan Dictionary"],
      ["com.vot.vot", "Voice of Tibet"],
      ["com.newsapp.voicefortibet", "Tibet Tribune"],
      ["com.bigkidsapps.tibetanmantras", "Tibetan Buddhist Mantras"],    
      ["cn.wps.moffice_eng","WPS Office-PDF,Word,Excel,PPT"],
      ["com.android.vending","Google Play Store","https://developer.android.com/distribute/marketing-tools/linking-to-google-play"],
      ["net.oneplus.weather","OnePlus Weather"],
      ["com.oneplus.gallery","OnePlus Gallery"],
      ["com.oneplus.filemanager","OnePlus File Manager"],
      ["com.oplus.gesture", "OPPO Gestures & Motions"],
      ["com.oplus.camera", "OPPO Camera"],
      ["com.coloros.safecenter", "ColorOS Phone Manager"],
      ["com.coloros.gallery3d", "ColorOS Photos"],
      ["com.oneplus.launcher", "OnePlus System Launcher"],
      ["com.sec.android.app.launcher", "Samsung One UI Home"],
      ["com.samsung.android.lool", "Samsung Device Care"],
      ["com.samsung.android.dialer", "Samsung Phone"],
      ["com.miui.home", "Xiaomi MIUI System Launcher"],
      ["com.miui.securitycenter", "Xiaomi Security App"],
      ["com.miui.gallery", "Xiaomi Gallery"],
      ["com.huawei.android.launcher", "Huawei EMUI Launcher"],
      ["com.android.systemui", "Android System UI"],
      ["com.android.settings", "Android Settings"],
      ["com.android.bluetooth", "Android Bluetooth Service"],
      ["com.android.nfc", "Android NFC Service"],
      ["com.google.android.packageinstaller", "Android Package Installer"],
      ["com.factory.mmigroup", "Hardware MMI Factory Test"],
      ["com.android.cts.priv.ctsshim", "Android CTS Shim"],
      ["com.qualcomm.qti.qms.service.telemetry", "Qualcomm Telemetry Service"],
      ["com.google.android.youtube", "YouTube"],
      ["com.android.internal.display.cutout.emulation.corner", "Display Cutout Emulation (Corner)"],
      ["com.google.android.ext.services", "Google Android Shared Library Services"],
      ["com.qualcomm.qti.improvetouch.service", "Qualcomm Touch Improvement Service"],
      ["com.android.internal.display.cutout.emulation.double", "Display Cutout Emulation (Double)"],
      ["com.android.providers.telephony", "Telephony Storage Provider"],
      ["com.android.dynsystem", "Dynamic System Updates (DSU)"],
      ["com.android.theme.icon.pebble", "Pebble Icon Shape Overlay"],
      ["com.google.android.googlequicksearchbox", "Google"],
      ["com.android.providers.calendar", "Calendar Storage Provider"],
      ["com.android.providers.media", "Media Storage Provider"],
      ["com.qti.service.colorservice", "Qualcomm Display Color Service"],
      ["com.google.android.onetimeinitializer", "Google One Time Initializer"],
      ["com.google.android.ext.shared", "Android Shared Services"],
      ["com.android.internal.systemui.navbar.gestural_wide_back", "Gesture Navigation Wide Back Overlay"],
      ["com.android.wallpapercropper", "Wallpaper Cropper"],
      ["com.bsp.catchlog", "BSP Log Capture Tool"],
      ["com.android.theme.icon.vessel", "Vessel Icon Shape Overlay"],
      ["com.xiaomi.cameratools", "Xiaomi Camera Tools"],
      ["com.android.theme.color.cinnamon", "Cinnamon Theme Color Overlay"],
      ["com.android.protips", "Android ProTips"],
      ["com.android.theme.icon_pack.rounded.systemui", "Rounded SystemUI Icon Pack Overlay"],
      ["com.android.theme.icon.taperedrect", "Tapered Rectangle Icon Shape Overlay"],
      ["com.wt.secret_code_manager", "Wingtech Secret Code Manager"],
      ["com.android.externalstorage", "External Storage Provider"],
      ["com.qualcomm.uimremoteclient", "Qualcomm UIM Remote Client"],
      ["com.android.htmlviewer", "HTML Viewer"],
      ["com.factory.cit", "Factory Hardware Diagnostic (CIT)"],
      ["com.qualcomm.qti.uceShimService", "Qualcomm UCE Shim Service"],
      ["com.android.companiondevicemanager", "Companion Device Manager"],
      ["com.android.mms.service", "MMS Service"],
      ["com.qualcomm.qti.qms.service.connectionsecurity", "Qualcomm Connection Security Service"],
      ["com.android.providers.downloads", "Download Manager Provider"],
      ["com.google.android.apps.messaging", "Google Messages"],
      ["com.android.theme.icon_pack.rounded.android", "Rounded Android Icon Pack Overlay"],
      ["vendor.qti.hardware.cacert.server", "Qualcomm CA Certificate Server"],
      ["com.qualcomm.qti.telephonyservice", "Qualcomm Telephony Service"],
      ["com.android.partnerbrowsercustomizations.tmobile", "Browser Customizations (T-Mobile)"],
      ["com.android.theme.icon_pack.circular.themepicker", "Circular Theme Picker Icon Pack Overlay"],
      ["vendor.qti.iwlan", "Qualcomm IWLAN Service"],
      ["com.google.android.configupdater", "Google Config Updater"],
      ["com.google.android.overlay.modules.permissioncontroller", "Permission Controller Overlay"],
      ["com.android.ons", "Opportunistic Network Service (OppNet)"],
      ["com.android.stk", "SIM Tool Kit"],
      ["com.android.launcher3", "Android System Launcher3"],
      ["com.android.backupconfirm", "Android Backup Confirmation"],
      ["com.mmigroup.fmradio", "MMI Group FM Radio"],
      ["com.google.android.deskclock", "Clock"],
      ["com.android.internal.systemui.navbar.twobutton", "Two-Button Navigation Overlay"],
      ["org.codeaurora.ims", "Code Aurora IMS Service (VoLTE/Wi-Fi Calling)"],
      ["com.android.statementservice", "Android Statement Service"],
      ["com.google.android.gm", "Gmail"],
      ["android.overlay.target", "Android Overlay Target"],
      ["com.google.android.apps.tachyon", "Google Meet"],
      ["com.google.android.overlay.gmsconfig.common", "Google Mobile Services Config Overlay"],
      ["com.qti.pasrservice", "Qualcomm PASR Service"],
      ["com.android.settings.intelligence", "Android Settings Intelligence"],
      ["com.android.internal.systemui.navbar.gestural_extra_wide_back", "Gesture Navigation Extra Wide Back Overlay"],
      ["com.google.android.permissioncontroller", "Android Permission Controller"],
      ["com.wingtech.setupwizardext", "Wingtech Setup Wizard Extension"],
      ["com.qualcomm.qti.dynamicddsservice", "Qualcomm Dynamic DDS Service"],
      ["com.google.android.setupwizard", "Android Setup Wizard"],
      ["com.qualcomm.qcrilmsgtunnel", "Qualcomm QCRIL Message Tunnel"],
      ["com.android.providers.settings", "Settings Storage Provider"],
      ["com.android.sharedstoragebackup", "Shared Storage Backup"],
      ["com.android.printspooler", "Android Print Spooler"],
      ["com.oplus.games", "OPPO Games"],
      ["com.oplus.pay", "OPPO Pay"],
      ["com.coloros.smartsidebar", "ColorOS Smart Sidebar"],
      ["com.oplus.encryption", "OPPO Encryption"],
      ["com.samsung.android.mcfds", "Samsung Multi Connectivity (MCF)"],
      ["prod.maasify.evian", "ÉVA'D Transport App"],
      ["com.samsung.android.globalpostprocmgr", "Samsung Global Post Processing Manager"],
      ["com.samsung.android.emergency", "Samsung Emergency SOS"],
      ["com.android.mtp", "Android MTP Host"],
      ["com.android.internal.display.cutout.emulation.tall", "Display Cutout Emulation (Tall)"],
      ["com.sec.facatfunction", "Samsung Factory Auto Test"],
      ["com.samsung.android.video", "Samsung Video Player"],
      ["com.samsung.android.knox.analytics.uploader", "Samsung Knox Analytics Uploader"],
      ["com.google.android.modulemetadata", "Google Module Metadata"],
      ["com.google.android.cellbroadcastreceiver", "Google Cell Broadcast Receiver"],
      ["com.sec.android.app.samsungapps", "Galaxy Store"],
      ["com.google.android.overlay.gmsconfig.geotz", "GMS Config Geo Timezone Overlay"],
      ["com.samsung.android.wifi.softapwpathree.resources", "Samsung Wi-Fi SoftAP WPA3 Resources"],
      ["com.android.shell", "Android Shell"],
      ["com.samsung.android.sdk.handwriting", "Samsung Handwriting SDK"],
      ["com.samsung.internal.systemui.navbar.sec_gestural_no_hint", "Samsung Gestural Nav No Hint Overlay"],
      ["com.android.wallpaperbackup", "Android Wallpaper Backup"],
      ["com.google.android.as", "Android System Intelligence"],
      ["com.android.localtransport", "Android Local Transport"],
      ["com.samsung.android.knox.mpos", "Samsung Knox mPOS"],
      ["com.google.android.ondevicepersonalization.services", "Google On-Device Personalization Services"],
      ["com.google.android.documentsui", "Google Files (DocumentsUI)"],
      ["com.samsung.android.samsungpassautofill", "Samsung Pass Autofill"],
      ["com.sec.android.daemonapp", "Samsung Weather Daemon"],
      ["com.google.android.overlay.modules.healthfitness.forframework", "Health & Fitness Framework Overlay"],
      ["com.samsung.android.smartcallprovider", "Samsung Smart Call Provider"],
      ["com.android.phone", "Android Phone (Telephony)"],
      ["com.samsung.android.themecenter", "Galaxy Themes"],
      ["org.visorando.android", "Visorando Walking Routes"],
      ["com.google.android.sdksandbox", "Google SDK Sandbox"],
      ["com.samsung.safetyinformation", "Samsung Safety Information"],
      ["com.samsung.android.knox.zt.framework", "Samsung Knox Zero Trust Framework"],
      ["com.samsung.android.bixby.ondevice.frfr", "Samsung Bixby On-Device (fr-FR)"],
      ["com.facebook.appmanager", "Meta App Manager"],
      ["com.samsung.SMT.lang_it_it_f00", "Samsung TTS Italian Voice Data"],
      ["com.android.server.telecom.auto_generated_rro_product__", "Android Telecom Product Overlay"],
      ["com.android.providers.telephony.auto_generated_characteristics_rro", "Telephony Characteristics Overlay"],
      ["com.google.android.apps.bard", "Google Gemini"],
      ["com.samsung.SMT.lang_ru_ru_f00", "Samsung TTS Russian Voice Data"],
      ["com.sec.usbsettings", "Samsung USB Settings"],
      ["com.samsung.android.mtp", "Samsung MTP Service"],
      ["com.samsung.android.beaconmanager", "Samsung Beacon Manager"],
      ["com.oplus.sau", "OPPO System Upgrade Services"],
      ["com.oneplus.backuprestore", "OnePlus Clone Phone"],
      ["com.samsung.android.app.updatecenter", "Samsung App Update Center"],
      ["com.facebook.system", "Meta (Facebook) System Framework"],
      ["com.heytap.market", "HeyTap App Market (OPPO)"],
      ["com.indus.appstore", "Indus Appstore"],
      ["com.motorola.installer", "Motorola App Installer"],
      ["com.dti.motorola", "Motorola Moto App Manager (Digital Turbine)"],
      ["com.sec.android.easyMover", "Samsung Smart Switch Mobile"],
      ["com.samsung.android.spay", "Samsung Pay"],
      ["com.aura.oobe.lenovo", "Lenovo Aura (Digital Turbine Setup)"],
      ["com.lenovo.tbengine", "Lenovo TB Engine"],
      ["com.tblenovo.lenovowhatsnew", "Lenovo What's New"],
      ["com.android.emergency", "Android Emergency Info"],
      ["com.zui.keyboardupdate.olympia", "ZUI Keyboard Update (Lenovo)"],
      ["in.startv.hotstar", "Disney+ Hotstar"],
      ["com.google.android.overlay.gmsconfig.searchselector", "GMS Config Search Selector Overlay"]
  ];
  const names = new Map(rows.map(([id, name, url]) => [id, Object.freeze({
    name, matched_package: id, match_method: 'exact-package-id',
    source_url: url || listingUrl(id),
    source_title: url ? 'F-Droid package listing' : 'Google Play app listing',
    checked_at: CHECKED_AT, catalogue_version: VERSION, scope: 'app-name-only',
  })]));
  if (names.size !== rows.length) throw new Error('Duplicate package ID in name catalogue.');

  function lookup(id, origin = {}) {
    const match = names.get(id);
    if (match) return { ...match };
    if (origin.match_method === 'exact-package-id' && origin.matched_package === id && origin.app_name) {
      return {
        name: origin.app_name, matched_package: id, match_method: 'exact-package-id',
        source_url: origin.sources?.[0]?.url || null,
        source_title: origin.sources?.[0]?.title || 'Publisher catalogue',
        checked_at: origin.checked_at || null, catalogue_version: origin.catalogue_version || null,
        scope: 'publisher-catalogue-name',
      };
    }
    return null;
  }

  function metadata() {
    return { version: VERSION, checked_at: CHECKED_AT, rule_count: names.size,
      scope: 'Exact-ID app names, independent of publisher and country classifications.',
      limitation: 'Store names can change and can differ from the installed label. Unmatched IDs need collector labels or additional verified entries.' };
  }
  return Object.freeze({ lookup, metadata, listingUrl });
})();
